version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout

      # generate and build project to test
      - run: curl https://raw.githubusercontent.com/kudzu-cms/kudzu/kudzu-dev/.circleci/test-setup.sh | sh

      # run tests
      - run: curl https://raw.githubusercontent.com/kudzu-cms/kudzu/kudzu-dev/.circleci/test-run.sh | sh

