theme: material
site_name: kudzu
docs_dir: src
site_dir: build
repo_name: kudzu-cms/kudzu
repo_url: https://github.com/kudzu-cms/kudzu

markdown_extensions:
      - codehilite(linenums=false)
      - meta
      - admonition
      - toc(permalink=true)

google_analytics:
      - 'UA-98609560-1'
      - auto

extra:
  palette:
    primary: grey
    accent: light-blue
  social:
    - type: github
      link: https://github.com/kudzu-cms
    - type: twitter
      link: https://twitter.com/kudzu_cms
  logo: images/logo.png
